env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/react
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-empty-interface': off
  react/prop-types:
    - error
    - skipUndeclared: true
  react/self-closing-comp: error
